apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-secret-provider
  namespace: default
spec:
  provider: azure
  secretObjects:
    - secretName: "csi-fake-secrets"
      type: Opaque
      data:
        - objectName: test_secret
          key: test_secret
  parameters:
    objects: |
      array:
        - |
          objectName: test_secret
          objectType: secret
          objectVersion: ""
